services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      #만약 Docker 없이 로컬에서 스프링 부트를 실행한다면 localhost를 사용하지만,
      #Docker 컨테이너 환경에서는 서비스 이름(mysql)을 사용해야 합니다.
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/toodang
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: toodang
    volumes:
      - mysql-data:/var/lib/mysql
  openvidu:
    image: openvidu/openvidu-server:main
    container_name: openvidu-server
    ports:
      - "4443:4443"  # OpenVidu 서버 포트
    environment:
      - OPENVIDU_SECRET=toodang-openvidu-secret-key  # OpenVidu 서버 비밀키
      - DOMAIN_OR_PUBLIC_IP=auto   # 도메인 또는 공인 IP
      - CERTIFICATE_TYPE=selfsigned  # 인증서 타입
      - OPENVIDU_CDR=false
    volumes:
      - openvidu-data:/openvidu/recordings  # 녹화 파일 저장용 볼륨
volumes:
  mysql-data:  # 볼륨 정의